// Generated from: tests/features/sprint-3/order-status.feature
import { test } from "../../../../tests/steps/fixtures.ts";

test.describe('Order Status Tracking', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('the restaurant website is loaded', null, { page }); 
    await And('the store is currently open', null, { page }); 
    await And('the mock Clover server is running', null, { page }); 
  });
  
  test('Initial status shows Received', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('I view the order confirmation page', null, { page }); 
    await Then('the status tracker should show "Received" as the active step', null, { page }); 
    await And('"Preparing" and "Ready" should be greyed out', null, { page }); 
  });

  test('Status updates to Preparing', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await And('the order status is changed to "preparing" on Clover', null, { page }); 
    await When('I wait for the next status poll on the confirmation page', null, { page }); 
    await Then('the status tracker should show "Preparing" as the active step', null, { page }); 
    await And('"Received" should show a checkmark', null, { page }); 
  });

  test('Status updates to Ready', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await And('the order status is changed to "ready" on Clover', null, { page }); 
    await When('I wait for the next status poll on the confirmation page', null, { page }); 
    await Then('the status tracker should show "Ready" as the active step', null, { page }); 
    await And('a "Ready for Pickup!" banner should appear', null, { page }); 
    await And('"Received" and "Preparing" should show checkmarks', null, { page }); 
  });

  test('Cancelled order shows cancelled state', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await And('the order status is changed to "cancelled"', null, { page }); 
    await When('I wait for the next status poll', null, { page }); 
    await Then('the tracker should show "Cancelled"', null, { page }); 
    await And('a notice to call the restaurant should be displayed', null, { page }); 
  });

  test('Status polls every 30 seconds', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('I am on the confirmation page', null, { page }); 
    await Then('a status check request should be made approximately every 30 seconds', null, { page }); 
  });

  test('Polling stops at terminal status (ready)', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await And('the order status reaches "ready"', null, { page }); 
    await When('I wait beyond the next poll interval', null, { page }); 
    await Then('no additional status check requests should be made', null, { page }); 
  });

  test('Polling stops at terminal status (cancelled)', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await And('the order status reaches "cancelled"', null, { page }); 
    await When('I wait beyond the next poll interval', null, { page }); 
    await Then('no additional status check requests should be made', null, { page }); 
  });

  test('Each status transition is logged', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('the order goes through received, preparing, and ready', null, { page }); 
    await Then('the orderStatusEvents table should have 3 entries for this order', null, { page }); 
  });

  test('Status events record correct source', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('the status is updated via Clover', null, { page }); 
    await Then('the orderStatusEvent source should be "clover"', null, { page }); 
  });

  test('Initial status event has web source', async ({ Given, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await Then('the first orderStatusEvent should have status "received" and source "web"', null, { page }); 
  });

  test('Order number displayed prominently', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('I should see the order number in large text', null, { page }); 
  });

  test('Success message shown', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('I should see "Your order has been received!"', null, { page }); 
  });

  test('Items listed on confirmation', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order with "Lamb Laghman" and "Uyghur Polo"', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('I should see "Lamb Laghman" with its quantity and line total', null, { page }); 
    await And('I should see "Uyghur Polo" with its quantity and line total', null, { page }); 
  });

  test('Pickup time displayed', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order with ASAP pickup', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('I should see the pickup time in a readable format', null, { page }); 
  });

  test('Customer info displayed', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order as "John Doe" with phone "2125551234"', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('I should see "John Doe" and the phone number', null, { page }); 
  });

  test('Totals displayed on confirmation', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('I should see the subtotal, tax, and total', null, { page }); 
  });

  test('Phone link for calling restaurant', async ({ Given, When, Then, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await When('I view the "Need to call us?" section', null, { page }); 
    await Then('the phone number should be a clickable tel link', null, { page }); 
  });

  test('Invalid order ID shows not found', async ({ When, Then, page }) => { 
    await When('I navigate to "/order/nonexistent-id"', null, { page }); 
    await Then('I should see "Order not found"', null, { page }); 
  });

  test('Status page works when Clover sync failed', async ({ Given, When, Then, And, page }) => { 
    await Given('I have placed an order', null, { page }); 
    await And('the Clover sync failed', null, { page }); 
    await When('I view the confirmation page', null, { page }); 
    await Then('the page should still load correctly', null, { page }); 
    await And('the status should show "Received"', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests/features/sprint-3/order-status.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":13,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"When I view the order confirmation page","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"Then the status tracker should show \"Received\" as the active step","stepMatchArguments":[{"group":{"start":31,"value":"\"Received\"","children":[{"start":32,"value":"Received","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"And \"Preparing\" and \"Ready\" should be greyed out","stepMatchArguments":[{"group":{"start":0,"value":"\"Preparing\"","children":[{"start":1,"value":"Preparing","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":16,"value":"\"Ready\"","children":[{"start":17,"value":"Ready","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":19,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":20,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":21,"keywordType":"Context","textWithKeyword":"And the order status is changed to \"preparing\" on Clover","stepMatchArguments":[{"group":{"start":31,"value":"\"preparing\"","children":[{"start":32,"value":"preparing","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When I wait for the next status poll on the confirmation page","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then the status tracker should show \"Preparing\" as the active step","stepMatchArguments":[{"group":{"start":31,"value":"\"Preparing\"","children":[{"start":32,"value":"Preparing","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"And \"Received\" should show a checkmark","stepMatchArguments":[{"group":{"start":0,"value":"\"Received\"","children":[{"start":1,"value":"Received","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":27,"pickleLine":26,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"And the order status is changed to \"ready\" on Clover","stepMatchArguments":[{"group":{"start":31,"value":"\"ready\"","children":[{"start":32,"value":"ready","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When I wait for the next status poll on the confirmation page","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then the status tracker should show \"Ready\" as the active step","stepMatchArguments":[{"group":{"start":31,"value":"\"Ready\"","children":[{"start":32,"value":"Ready","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"And a \"Ready for Pickup!\" banner should appear","stepMatchArguments":[{"group":{"start":2,"value":"\"Ready for Pickup!\"","children":[{"start":3,"value":"Ready for Pickup!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"And \"Received\" and \"Preparing\" should show checkmarks","stepMatchArguments":[{"group":{"start":0,"value":"\"Received\"","children":[{"start":1,"value":"Received","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":15,"value":"\"Preparing\"","children":[{"start":16,"value":"Preparing","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":34,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":35,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":36,"keywordType":"Context","textWithKeyword":"And the order status is changed to \"cancelled\"","stepMatchArguments":[{"group":{"start":31,"value":"\"cancelled\"","children":[{"start":32,"value":"cancelled","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I wait for the next status poll","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then the tracker should show \"Cancelled\"","stepMatchArguments":[{"group":{"start":24,"value":"\"Cancelled\"","children":[{"start":25,"value":"Cancelled","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"And a notice to call the restaurant should be displayed","stepMatchArguments":[]}]},
  {"pwTestLine":44,"pickleLine":43,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When I am on the confirmation page","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then a status check request should be made approximately every 30 seconds","stepMatchArguments":[]}]},
  {"pwTestLine":50,"pickleLine":48,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":49,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":50,"keywordType":"Context","textWithKeyword":"And the order status reaches \"ready\"","stepMatchArguments":[{"group":{"start":25,"value":"\"ready\"","children":[{"start":26,"value":"ready","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":51,"keywordType":"Action","textWithKeyword":"When I wait beyond the next poll interval","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":52,"keywordType":"Outcome","textWithKeyword":"Then no additional status check requests should be made","stepMatchArguments":[]}]},
  {"pwTestLine":57,"pickleLine":54,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":56,"keywordType":"Context","textWithKeyword":"And the order status reaches \"cancelled\"","stepMatchArguments":[{"group":{"start":25,"value":"\"cancelled\"","children":[{"start":26,"value":"cancelled","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When I wait beyond the next poll interval","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then no additional status check requests should be made","stepMatchArguments":[]}]},
  {"pwTestLine":64,"pickleLine":62,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":63,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When the order goes through received, preparing, and ready","stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the orderStatusEvents table should have 3 entries for this order","stepMatchArguments":[{"group":{"start":40,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":70,"pickleLine":67,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":68,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":69,"keywordType":"Action","textWithKeyword":"When the status is updated via Clover","stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":70,"keywordType":"Outcome","textWithKeyword":"Then the orderStatusEvent source should be \"clover\"","stepMatchArguments":[{"group":{"start":38,"value":"\"clover\"","children":[{"start":39,"value":"clover","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":76,"pickleLine":72,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":73,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"Then the first orderStatusEvent should have status \"received\" and source \"web\"","stepMatchArguments":[{"group":{"start":46,"value":"\"received\"","children":[{"start":47,"value":"received","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"web\"","children":[{"start":69,"value":"web","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":81,"pickleLine":78,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":82,"gherkinStepLine":79,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":80,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"Then I should see the order number in large text","stepMatchArguments":[]}]},
  {"pwTestLine":87,"pickleLine":83,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":89,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":90,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then I should see \"Your order has been received!\"","stepMatchArguments":[{"group":{"start":13,"value":"\"Your order has been received!\"","children":[{"start":14,"value":"Your order has been received!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":93,"pickleLine":88,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":94,"gherkinStepLine":89,"keywordType":"Context","textWithKeyword":"Given I have placed an order with \"Lamb Laghman\" and \"Uyghur Polo\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Lamb Laghman\"","children":[{"start":29,"value":"Lamb Laghman","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"\"Uyghur Polo\"","children":[{"start":48,"value":"Uyghur Polo","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":95,"gherkinStepLine":90,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":91,"keywordType":"Outcome","textWithKeyword":"Then I should see \"Lamb Laghman\" with its quantity and line total","stepMatchArguments":[{"group":{"start":13,"value":"\"Lamb Laghman\"","children":[{"start":14,"value":"Lamb Laghman","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"And I should see \"Uyghur Polo\" with its quantity and line total","stepMatchArguments":[{"group":{"start":13,"value":"\"Uyghur Polo\"","children":[{"start":14,"value":"Uyghur Polo","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":100,"pickleLine":94,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given I have placed an order with ASAP pickup","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":103,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then I should see the pickup time in a readable format","stepMatchArguments":[]}]},
  {"pwTestLine":106,"pickleLine":99,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"Given I have placed an order as \"John Doe\" with phone \"2125551234\"","stepMatchArguments":[{"group":{"start":26,"value":"\"John Doe\"","children":[{"start":27,"value":"John Doe","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"2125551234\"","children":[{"start":49,"value":"2125551234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then I should see \"John Doe\" and the phone number","stepMatchArguments":[{"group":{"start":13,"value":"\"John Doe\"","children":[{"start":14,"value":"John Doe","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":112,"pickleLine":104,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":113,"gherkinStepLine":105,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":114,"gherkinStepLine":106,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":115,"gherkinStepLine":107,"keywordType":"Outcome","textWithKeyword":"Then I should see the subtotal, tax, and total","stepMatchArguments":[]}]},
  {"pwTestLine":118,"pickleLine":109,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":110,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":120,"gherkinStepLine":111,"keywordType":"Action","textWithKeyword":"When I view the \"Need to call us?\" section","stepMatchArguments":[{"group":{"start":11,"value":"\"Need to call us?\"","children":[{"start":12,"value":"Need to call us?","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":121,"gherkinStepLine":112,"keywordType":"Outcome","textWithKeyword":"Then the phone number should be a clickable tel link","stepMatchArguments":[]}]},
  {"pwTestLine":124,"pickleLine":114,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":125,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"When I navigate to \"/order/nonexistent-id\"","stepMatchArguments":[{"group":{"start":14,"value":"\"/order/nonexistent-id\"","children":[{"start":15,"value":"/order/nonexistent-id","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then I should see \"Order not found\"","stepMatchArguments":[{"group":{"start":13,"value":"\"Order not found\"","children":[{"start":14,"value":"Order not found","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":129,"pickleLine":120,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And the mock Clover server is running","isBg":true,"stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":121,"keywordType":"Context","textWithKeyword":"Given I have placed an order","stepMatchArguments":[]},{"pwStepLine":131,"gherkinStepLine":122,"keywordType":"Context","textWithKeyword":"And the Clover sync failed","stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":123,"keywordType":"Action","textWithKeyword":"When I view the confirmation page","stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":124,"keywordType":"Outcome","textWithKeyword":"Then the page should still load correctly","stepMatchArguments":[]},{"pwStepLine":134,"gherkinStepLine":125,"keywordType":"Outcome","textWithKeyword":"And the status should show \"Received\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Received\"","children":[{"start":24,"value":"Received","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end