// Generated from: tests/features/sprint-2/checkout.feature
import { test } from "../../../../tests/steps/fixtures.ts";

test.describe('Checkout', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('the restaurant website is loaded', null, { page }); 
    await And('the store is currently open', null, { page }); 
    await And('I have items in my cart', null, { page }); 
    await And('I navigate to "/checkout"', null, { page }); 
  });
  
  test('Complete checkout with valid info', async ({ When, Then, And, page }) => { 
    await When('I enter "John Doe" as the customer name', null, { page }); 
    await And('I enter "2125551234" as the phone number', null, { page }); 
    await And('I select "ASAP" as the pickup time', null, { page }); 
    await And('I tap "Place Order"', null, { page }); 
    await Then('I should see the order confirmation page', null, { page }); 
  });

  test('Checkout requires name', async ({ When, Then, And, page }) => { 
    await When('I leave the name field empty', null, { page }); 
    await And('I tap "Place Order"', null, { page }); 
    await Then('I should see an error "Name is required" below the name field', null, { page }); 
  });

  test('Checkout requires phone', async ({ When, Then, And, page }) => { 
    await When('I enter "John Doe" as the name', null, { page }); 
    await And('I leave the phone field empty', null, { page }); 
    await And('I tap "Place Order"', null, { page }); 
    await Then('I should see an error below the phone field', null, { page }); 
  });

  test('Invalid phone number shows error', async ({ When, Then, And, page }) => { 
    await When('I enter "123" as the phone number', null, { page }); 
    await And('I blur the phone field', null, { page }); 
    await Then('I should see an error "Enter a valid phone number" below the phone field', null, { page }); 
  });

  test('Phone number auto-formats', async ({ When, Then, page }) => { 
    await When('I type "2125551234" in the phone field', null, { page }); 
    await Then('the phone field should display "(212) 555-1234"', null, { page }); 
  });

  test('Valid email is accepted', async ({ When, Then, page }) => { 
    await When('I enter "john@example.com" in the email field', null, { page }); 
    await Then('no error should be shown for the email field', null, { page }); 
  });

  test('Invalid email shows error', async ({ When, Then, And, page }) => { 
    await When('I enter "not-an-email" in the email field', null, { page }); 
    await And('I blur the email field', null, { page }); 
    await Then('I should see an error "Enter a valid email" below the email field', null, { page }); 
  });

  test('Email is optional', async ({ When, Then, And, page }) => { 
    await When('I leave the email field empty', null, { page }); 
    await And('I fill in valid name and phone', null, { page }); 
    await And('I tap "Place Order"', null, { page }); 
    await Then('no error should be shown for the email field', null, { page }); 
  });

  test('Name minimum length validation', async ({ When, Then, And, page }) => { 
    await When('I enter "A" as the customer name', null, { page }); 
    await And('I blur the name field', null, { page }); 
    await Then('I should see an error about minimum length', null, { page }); 
  });

  test('Select ASAP pickup time', async ({ When, Then, And, page }) => { 
    await When('I view the pickup time selector', null, { page }); 
    await Then('"ASAP" should be selected by default', null, { page }); 
    await And('it should display an estimated ready time like "ASAP (~20 min)"', null, { page }); 
  });

  test('Select scheduled pickup time', async ({ When, Then, page }) => { 
    await When('I open the pickup time selector', null, { page }); 
    await Then('I should see time slots in 15-minute increments', null, { page }); 
    await When('I select a specific time slot', null, { page }); 
    await Then('that time slot should be marked as selected', null, { page }); 
  });

  test('No past time slots shown', async ({ When, Then, page }) => { 
    await When('I view the available pickup time slots', null, { page }); 
    await Then('no time slot should be in the past', null, { page }); 
  });

  test('Time slots stop before closing', async ({ When, Then, page }) => { 
    await When('I view the available pickup time slots', null, { page }); 
    await Then('the last available slot should be at least 30 minutes before closing time', null, { page }); 
  });

  test('Order summary shows all items', async ({ When, Then, And, page }) => { 
    await When('I view the order summary section', null, { page }); 
    await Then('I should see all cart items with names, quantities, and line totals', null, { page }); 
    await And('I should see the subtotal', null, { page }); 
    await And('I should see the estimated tax', null, { page }); 
    await And('I should see the estimated total', null, { page }); 
  });

  test('Order summary collapsed on mobile by default', async ({ Given, When, Then, page }) => { 
    await Given('I am viewing the site at 375px viewport width', null, { page }); 
    await When('I view the order summary', null, { page }); 
    await Then('it should be collapsed by default', null, { page }); 
  });

  test('Order summary expanded on desktop', async ({ Given, When, Then, page }) => { 
    await Given('I am viewing the site at 1280px viewport width', null, { page }); 
    await When('I view the order summary', null, { page }); 
    await Then('it should be expanded by default', null, { page }); 
  });

  test('Add kitchen note', async ({ When, Then, And, page }) => { 
    await When('I enter "Please make everything mild" in the kitchen note field', null, { page }); 
    await Then('the text should be accepted'); 
    await And('a character counter should be visible', null, { page }); 
  });

  test('Kitchen note has character limit', async ({ When, Then, page }) => { 
    await When('I type more than 500 characters in the kitchen note field', null, { page }); 
    await Then('the input should stop at 500 characters', null, { page }); 
  });

  test('Payment notice shows pay at pickup', async ({ When, Then, page }) => { 
    await When('I view the checkout page'); 
    await Then('I should see a notice "Payment will be collected at pickup"', null, { page }); 
  });

  test('Place order shows confirmation', async ({ When, Then, And, page }) => { 
    await When('I fill in all required fields with valid data', null, { page }); 
    await And('I tap "Place Order"', null, { page }); 
    await Then('I should be navigated to the order confirmation page', null, { page }); 
    await And('I should see an order number', null, { page }); 
  });

  test('Double-click place order only creates one order (idempotency)', async ({ When, Then, And, page }) => { 
    await When('I fill in all required fields with valid data', null, { page }); 
    await And('I rapidly click "Place Order" twice', null, { page }); 
    await Then('only one order should be created', null, { page }); 
    await And('I should see only one confirmation', null, { page }); 
  });

  test('Place Order button shows loading state', async ({ When, Then, And, page }) => { 
    await When('I fill in all required fields with valid data', null, { page }); 
    await And('I tap "Place Order"', null, { page }); 
    await Then('the button should show a loading spinner', null, { page }); 
    await And('the button should be disabled during submission', null, { page }); 
  });

  test('Empty cart redirects from checkout', async ({ Given, When, Then, page }) => { 
    await Given('the cart is empty', null, { page }); 
    await When('I navigate to "/checkout"', null, { page }); 
    await Then('I should be redirected to "/cart" or see a message to add items', null, { page }); 
  });

  test('Checkout page title is correct', async ({ Then, page }) => { 
    await Then('the page title should be "Checkout | Tengri Tagh Uyghur Cuisine"', null, { page }); 
  });

  test.describe('Checkout is fully responsive', () => {

    test('Example #1', async ({ Given, When, Then, And, page }) => { 
      await Given('I am viewing the site at 375px viewport width', null, { page }); 
      await When('the checkout page loads', null, { page }); 
      await Then('there should be no horizontal overflow', null, { page }); 
      await And('all form fields should be usable', null, { page }); 
    });

    test('Example #2', async ({ Given, When, Then, And, page }) => { 
      await Given('I am viewing the site at 768px viewport width', null, { page }); 
      await When('the checkout page loads', null, { page }); 
      await Then('there should be no horizontal overflow', null, { page }); 
      await And('all form fields should be usable', null, { page }); 
    });

    test('Example #3', async ({ Given, When, Then, And, page }) => { 
      await Given('I am viewing the site at 1280px viewport width', null, { page }); 
      await When('the checkout page loads', null, { page }); 
      await Then('there should be no horizontal overflow', null, { page }); 
      await And('all form fields should be usable', null, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests/features/sprint-2/checkout.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":14,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"When I enter \"John Doe\" as the customer name","stepMatchArguments":[{"group":{"start":8,"value":"\"John Doe\"","children":[{"start":9,"value":"John Doe","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"And I enter \"2125551234\" as the phone number","stepMatchArguments":[{"group":{"start":8,"value":"\"2125551234\"","children":[{"start":9,"value":"2125551234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":17,"keywordType":"Action","textWithKeyword":"And I select \"ASAP\" as the pickup time","stepMatchArguments":[{"group":{"start":9,"value":"\"ASAP\"","children":[{"start":10,"value":"ASAP","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"And I tap \"Place Order\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Place Order\"","children":[{"start":7,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then I should see the order confirmation page","stepMatchArguments":[]}]},
  {"pwTestLine":21,"pickleLine":21,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When I leave the name field empty","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"And I tap \"Place Order\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Place Order\"","children":[{"start":7,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see an error \"Name is required\" below the name field","stepMatchArguments":[{"group":{"start":22,"value":"\"Name is required\"","children":[{"start":23,"value":"Name is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":27,"pickleLine":26,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When I enter \"John Doe\" as the name","stepMatchArguments":[{"group":{"start":8,"value":"\"John Doe\"","children":[{"start":9,"value":"John Doe","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"And I leave the phone field empty","stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"And I tap \"Place Order\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Place Order\"","children":[{"start":7,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then I should see an error below the phone field","stepMatchArguments":[]}]},
  {"pwTestLine":34,"pickleLine":32,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":35,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When I enter \"123\" as the phone number","stepMatchArguments":[{"group":{"start":8,"value":"\"123\"","children":[{"start":9,"value":"123","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"And I blur the phone field","stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then I should see an error \"Enter a valid phone number\" below the phone field","stepMatchArguments":[{"group":{"start":22,"value":"\"Enter a valid phone number\"","children":[{"start":23,"value":"Enter a valid phone number","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":40,"pickleLine":37,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"When I type \"2125551234\" in the phone field","stepMatchArguments":[{"group":{"start":7,"value":"\"2125551234\"","children":[{"start":8,"value":"2125551234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then the phone field should display \"(212) 555-1234\"","stepMatchArguments":[{"group":{"start":31,"value":"\"(212) 555-1234\"","children":[{"start":32,"value":"(212) 555-1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":45,"pickleLine":41,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When I enter \"john@example.com\" in the email field","stepMatchArguments":[{"group":{"start":8,"value":"\"john@example.com\"","children":[{"start":9,"value":"john@example.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then no error should be shown for the email field","stepMatchArguments":[]}]},
  {"pwTestLine":50,"pickleLine":45,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When I enter \"not-an-email\" in the email field","stepMatchArguments":[{"group":{"start":8,"value":"\"not-an-email\"","children":[{"start":9,"value":"not-an-email","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"And I blur the email field","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":48,"keywordType":"Outcome","textWithKeyword":"Then I should see an error \"Enter a valid email\" below the email field","stepMatchArguments":[{"group":{"start":22,"value":"\"Enter a valid email\"","children":[{"start":23,"value":"Enter a valid email","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":56,"pickleLine":50,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":51,"keywordType":"Action","textWithKeyword":"When I leave the email field empty","stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"And I fill in valid name and phone","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"And I tap \"Place Order\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Place Order\"","children":[{"start":7,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then no error should be shown for the email field","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":56,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When I enter \"A\" as the customer name","stepMatchArguments":[{"group":{"start":8,"value":"\"A\"","children":[{"start":9,"value":"A","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"And I blur the name field","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then I should see an error about minimum length","stepMatchArguments":[]}]},
  {"pwTestLine":69,"pickleLine":63,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When I view the pickup time selector","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then \"ASAP\" should be selected by default","stepMatchArguments":[{"group":{"start":0,"value":"\"ASAP\"","children":[{"start":1,"value":"ASAP","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"And it should display an estimated ready time like \"ASAP (~20 min)\"","stepMatchArguments":[{"group":{"start":47,"value":"\"ASAP (~20 min)\"","children":[{"start":48,"value":"ASAP (~20 min)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":75,"pickleLine":68,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":69,"keywordType":"Action","textWithKeyword":"When I open the pickup time selector","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":70,"keywordType":"Outcome","textWithKeyword":"Then I should see time slots in 15-minute increments","stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When I select a specific time slot","stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then that time slot should be marked as selected","stepMatchArguments":[]}]},
  {"pwTestLine":82,"pickleLine":74,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":83,"gherkinStepLine":75,"keywordType":"Action","textWithKeyword":"When I view the available pickup time slots","stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"Then no time slot should be in the past","stepMatchArguments":[]}]},
  {"pwTestLine":87,"pickleLine":78,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When I view the available pickup time slots","stepMatchArguments":[]},{"pwStepLine":89,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then the last available slot should be at least 30 minutes before closing time","stepMatchArguments":[{"group":{"start":43,"value":"30","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":92,"pickleLine":84,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When I view the order summary section","stepMatchArguments":[]},{"pwStepLine":94,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then I should see all cart items with names, quantities, and line totals","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"And I should see the subtotal","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"And I should see the estimated tax","stepMatchArguments":[]},{"pwStepLine":97,"gherkinStepLine":89,"keywordType":"Outcome","textWithKeyword":"And I should see the estimated total","stepMatchArguments":[]}]},
  {"pwTestLine":100,"pickleLine":91,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":101,"gherkinStepLine":92,"keywordType":"Context","textWithKeyword":"Given I am viewing the site at 375px viewport width","stepMatchArguments":[{"group":{"start":25,"value":"375","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":102,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When I view the order summary","stepMatchArguments":[]},{"pwStepLine":103,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then it should be collapsed by default","stepMatchArguments":[]}]},
  {"pwTestLine":106,"pickleLine":96,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":107,"gherkinStepLine":97,"keywordType":"Context","textWithKeyword":"Given I am viewing the site at 1280px viewport width","stepMatchArguments":[{"group":{"start":25,"value":"1280","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":108,"gherkinStepLine":98,"keywordType":"Action","textWithKeyword":"When I view the order summary","stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":99,"keywordType":"Outcome","textWithKeyword":"Then it should be expanded by default","stepMatchArguments":[]}]},
  {"pwTestLine":112,"pickleLine":103,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":113,"gherkinStepLine":104,"keywordType":"Action","textWithKeyword":"When I enter \"Please make everything mild\" in the kitchen note field","stepMatchArguments":[{"group":{"start":8,"value":"\"Please make everything mild\"","children":[{"start":9,"value":"Please make everything mild","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":114,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then the text should be accepted","stepMatchArguments":[]},{"pwStepLine":115,"gherkinStepLine":106,"keywordType":"Outcome","textWithKeyword":"And a character counter should be visible","stepMatchArguments":[]}]},
  {"pwTestLine":118,"pickleLine":108,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":119,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When I type more than 500 characters in the kitchen note field","stepMatchArguments":[{"group":{"start":17,"value":"500","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":120,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then the input should stop at 500 characters","stepMatchArguments":[{"group":{"start":25,"value":"500","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":123,"pickleLine":114,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":124,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"When I view the checkout page","stepMatchArguments":[]},{"pwStepLine":125,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then I should see a notice \"Payment will be collected at pickup\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Payment will be collected at pickup\"","children":[{"start":23,"value":"Payment will be collected at pickup","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":128,"pickleLine":120,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":121,"keywordType":"Action","textWithKeyword":"When I fill in all required fields with valid data","stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":122,"keywordType":"Action","textWithKeyword":"And I tap \"Place Order\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Place Order\"","children":[{"start":7,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":131,"gherkinStepLine":123,"keywordType":"Outcome","textWithKeyword":"Then I should be navigated to the order confirmation page","stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":124,"keywordType":"Outcome","textWithKeyword":"And I should see an order number","stepMatchArguments":[]}]},
  {"pwTestLine":135,"pickleLine":126,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":127,"keywordType":"Action","textWithKeyword":"When I fill in all required fields with valid data","stepMatchArguments":[]},{"pwStepLine":137,"gherkinStepLine":128,"keywordType":"Action","textWithKeyword":"And I rapidly click \"Place Order\" twice","stepMatchArguments":[{"group":{"start":16,"value":"\"Place Order\"","children":[{"start":17,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":138,"gherkinStepLine":129,"keywordType":"Outcome","textWithKeyword":"Then only one order should be created","stepMatchArguments":[]},{"pwStepLine":139,"gherkinStepLine":130,"keywordType":"Outcome","textWithKeyword":"And I should see only one confirmation","stepMatchArguments":[]}]},
  {"pwTestLine":142,"pickleLine":132,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":143,"gherkinStepLine":133,"keywordType":"Action","textWithKeyword":"When I fill in all required fields with valid data","stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":134,"keywordType":"Action","textWithKeyword":"And I tap \"Place Order\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Place Order\"","children":[{"start":7,"value":"Place Order","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":145,"gherkinStepLine":135,"keywordType":"Outcome","textWithKeyword":"Then the button should show a loading spinner","stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":136,"keywordType":"Outcome","textWithKeyword":"And the button should be disabled during submission","stepMatchArguments":[]}]},
  {"pwTestLine":149,"pickleLine":140,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":150,"gherkinStepLine":141,"keywordType":"Context","textWithKeyword":"Given the cart is empty","stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":142,"keywordType":"Action","textWithKeyword":"When I navigate to \"/checkout\"","stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":152,"gherkinStepLine":143,"keywordType":"Outcome","textWithKeyword":"Then I should be redirected to \"/cart\" or see a message to add items","stepMatchArguments":[{"group":{"start":26,"value":"\"/cart\"","children":[{"start":27,"value":"/cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":155,"pickleLine":145,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":156,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then the page title should be \"Checkout | Tengri Tagh Uyghur Cuisine\"","stepMatchArguments":[{"group":{"start":25,"value":"\"Checkout | Tengri Tagh Uyghur Cuisine\"","children":[{"start":26,"value":"Checkout | Tengri Tagh Uyghur Cuisine","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":161,"pickleLine":156,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":162,"gherkinStepLine":149,"keywordType":"Context","textWithKeyword":"Given I am viewing the site at 375px viewport width","stepMatchArguments":[{"group":{"start":25,"value":"375","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":163,"gherkinStepLine":150,"keywordType":"Action","textWithKeyword":"When the checkout page loads","stepMatchArguments":[]},{"pwStepLine":164,"gherkinStepLine":151,"keywordType":"Outcome","textWithKeyword":"Then there should be no horizontal overflow","stepMatchArguments":[]},{"pwStepLine":165,"gherkinStepLine":152,"keywordType":"Outcome","textWithKeyword":"And all form fields should be usable","stepMatchArguments":[]}]},
  {"pwTestLine":168,"pickleLine":157,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":169,"gherkinStepLine":149,"keywordType":"Context","textWithKeyword":"Given I am viewing the site at 768px viewport width","stepMatchArguments":[{"group":{"start":25,"value":"768","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":170,"gherkinStepLine":150,"keywordType":"Action","textWithKeyword":"When the checkout page loads","stepMatchArguments":[]},{"pwStepLine":171,"gherkinStepLine":151,"keywordType":"Outcome","textWithKeyword":"Then there should be no horizontal overflow","stepMatchArguments":[]},{"pwStepLine":172,"gherkinStepLine":152,"keywordType":"Outcome","textWithKeyword":"And all form fields should be usable","stepMatchArguments":[]}]},
  {"pwTestLine":175,"pickleLine":158,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the restaurant website is loaded","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the store is currently open","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I have items in my cart","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"And I navigate to \"/checkout\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/checkout\"","children":[{"start":15,"value":"/checkout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":176,"gherkinStepLine":149,"keywordType":"Context","textWithKeyword":"Given I am viewing the site at 1280px viewport width","stepMatchArguments":[{"group":{"start":25,"value":"1280","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":177,"gherkinStepLine":150,"keywordType":"Action","textWithKeyword":"When the checkout page loads","stepMatchArguments":[]},{"pwStepLine":178,"gherkinStepLine":151,"keywordType":"Outcome","textWithKeyword":"Then there should be no horizontal overflow","stepMatchArguments":[]},{"pwStepLine":179,"gherkinStepLine":152,"keywordType":"Outcome","textWithKeyword":"And all form fields should be usable","stepMatchArguments":[]}]},
]; // bdd-data-end